# Generated by Django 4.0.1 on 2022-02-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenhabitacion',
            name='habitacion',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='reserva',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.reserva', verbose_name='Reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestor',
            name='hospedaje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.hospedaje', verbose_name='Hospedaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenhabitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.tipohabitacion', verbose_name=' Tipo de Habitacion'),
            preserve_default=False,
        ),
    ]
