# Generated by Django 4.0.1 on 2022-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciohabitacion',
            options={'ordering': ['id'], 'verbose_name': 'Servicio de Habitacion', 'verbose_name_plural': 'Servicios de Habitaciones'},
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='habitaciones/%Y/%m/%d'),
        ),
    ]
