# Generated by Django 4.0.1 on 2022-03-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_imagenhabitacion_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
