# Generated by Django 4.0.1 on 2022-03-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_habitacion_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipohospedaje',
            old_name='name',
            new_name='nombre',
        ),
    ]
