# Generated by Django 4.0.1 on 2022-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_serviciohabitacion_options_habitacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='habitaciones/%Y/%m/%d'),
        ),
    ]
