# Generated by Django 4.0.1 on 2022-04-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_reserva_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='paid_out',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservita', to='erp.reserva', verbose_name='Reserva'),
        ),
    ]
