# Generated by Django 4.0.1 on 2022-04-14 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_remove_pagoreserva_paid_out_pagoreserva_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoreserva',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado_habitacion',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'Limpieza'), ('mantenimiento', 'Mantenimiento'), ('reservada', 'Reservada')], default='disponible', max_length=15, verbose_name='Estado Habitacion'),
        ),
        migrations.AlterField(
            model_name='pagoreserva',
            name='estado_pago',
            field=models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente'), ('sin cancelar', 'Sin Cancelar')], default='pendiente', max_length=25, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('sin confirmar', 'Sin Confirmar'), ('confirmada', 'Confirmada'), ('no ingreso', 'No Ingreso'), ('cancelada', 'Cancelada'), ('alojamiento terminado', 'Alojamiento Terminado')], default='sin confirmar', max_length=25, verbose_name='Estado de Reserva'),
        ),
    ]
