# Generated by Django 4.0.1 on 2022-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Carnet Extranjeria', 'Carnet Extranjeria')], default='DNI', max_length=25, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
