# Generated by Django 4.0.1 on 2022-03-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Documento'),
        ),
    ]
